Closes #109 (new branch based on latest main)
Roche/crmPack pull request #257
Opened 2022-06-14 15:41 UTC by gunhanb

Closes #109; New branch based on latest main. It contains initial new code for Rules - but it should be further completed.

2022-06-14 17:50 UTC, danielinteractive commented
@gunhanb @wwojciech can you please work together to get checks fixed and then merge? thanks!

2022-06-14 17:58 UTC, gunhanb commented
Hi Daniel,

This is done with @wwojciech actually. I am in contact with him to resolve this.


Sent from my iPhone

> On 14. Jun 2022, at 19:50, Daniel Sabanes Bove ***@***.***> wrote:
> 
> ﻿
> @gunhanb @wwojciech can you please work together to get checks fixed and then merge? thanks!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-06-15 13:25 UTC, wwojciech commented on R/Rules-class.R
> +    unacceptable_int = "numeric",
should not be an 'integer' ?

2022-06-15 13:29 UTC, wwojciech commented on R/Rules-validity.R
> +
I think this validation should be improved. For instance, 

1. what if condition in `if` clause is `FALSE`?
2. for `losses` please use `checkmate`
3. `overdose_int` - left bound in the interval is opened right? same for `unacceptable_int`.
4. lengths of `max_overdose_prob` and `losses` should also be verified.

2022-06-15 13:31 UTC, wwojciech requested changes
Looks good but some important changes are required.

2022-06-15 17:57 UTC, wwojciech commented on R/Rules-validity.R
> +
Sure; in particular `checkmate` provides a set of testing function `test_*` that we use to validate the objects.
For example 
```
test_numeric(object@weights, lower = 0, finite = TRUE, any.missing = FALSE, len = 2)
```
tests wether  `object@weights` is a numeric vector of length 2 without any missing values, with all values finite and greater than or equal to 0.

See more examples e.g. in `Model-validity.R` file.

2022-06-21 07:14 UTC, danielinteractive commented
@wwojciech @gunhanb how about you have another 1:1 session to finish this? so instead of review comments finish it together. just would be good to merge this. thanks

2022-06-21 16:06 UTC, wwojciech commented
> @wwojciech @gunhanb how about you have another 1:1 session to finish this? so instead of review comments finish it together. just would be good to merge this. thanks

Sure @danielinteractive , @gunhanb let me know please when it is convenient for you to have another 1:1 session. Tx!

2022-06-23 14:47 UTC, wwojciech commented
Thanks @gunhanb I see it now fails at some `linter` checking. Would you like me to correct these ones or you correct it by yourself?

2022-06-23 14:57 UTC, gunhanb commented
> Thanks @gunhanb I see it now fails at some `linter` checking. Would you like me to correct these ones or you correct it by yourself?

Would be great if you can finalize it? Sorry for the additional work!

2022-06-23 14:59 UTC, wwojciech commented
> > Thanks @gunhanb I see it now fails at some `linter` checking. Would you like me to correct these ones or you correct it by yourself?
> 
> Would be great if you can finalize it? Sorry for the additional work!

@gunhanb  - sure, no problem. So I will finish all the rest (including some cleanup and etc, if any) and then accept it.

2022-06-27 09:21 UTC, wwojciech submitted a review, later dismissed

2022-06-27 12:07 UTC, wwojciech commented
Hi @danielinteractive , I would merge this PR as it is now (without `nextBest`) to not loose its current good sync with the `main` that progresses quite fast. Then, `nextBest` can be created in a separate issue. What do you think?

2022-06-27 13:11 UTC, wwojciech commented
> @wwojciech can you maybe check if we lost the method somewhere in the process? e.g. did the old PR have this? I would not like to merge like it is now, feels a bit weird

Your right @danielinteractive, it is in the old PR ( https://github.com/Roche/crmPack/pull/139 ). Thanks for the hint! Unfortunately, it has no unit tests at all, and it needs to be cleaned up....

2022-06-27 15:15 UTC, wwojciech commented
I copied-pasted `nextBest` method for `NCRMLoss` but it fails on the examples provided.

@gunhanb - are you sure this below is correct?
```
#' @slot losses (`numeric`)\cr a vector specifying the loss function. If the
#'   `unacceptable` is provided, the vector length must be \eqn{4}, otherwise
#'   \eqn{3}.
```
The `nextBest` method you wrote fails, when specifying `losses` with this rule. I think it should be the opposite, i.e. if the `unacceptable` is provided, the vector length must be of length `3`, and otherwise it must be `4`. Can you please clarify this and check the implementation?

2022-06-28 15:57 UTC, wwojciech commented
> > I copied-pasted `nextBest` method for `NCRMLoss` but it fails on the examples provided.
> > @gunhanb - are you sure this below is correct?
> > ```
> > #' @slot losses (`numeric`)\cr a vector specifying the loss function. If the
> > #'   `unacceptable` is provided, the vector length must be \eqn{4}, otherwise
> > #'   \eqn{3}.
> > ```
> > 
> > The `nextBest` method you wrote fails, when specifying `losses` with this rule. I think it should be the opposite, i.e. if the `unacceptable` is provided, the vector length must be of length `3`, and otherwise it must be `4`. Or maybe this rule is OK and the `nextBest` method implementation needs to be corrected. Can you please clarify this and check the implementation?
> 
> Yes, you are absolutely right. It is a typo, it should be the other way around. When `unacceptable` is provided, the vector length must be of length `4`, and otherwise it must be `3`. Sorry for the mistake!

@gunhanb - sorry I am a bit confused, it is already like that (when `unacceptable` is provided, the vector length is of 
 length `4`, and otherwise it is be `3`). But you write in the same sentence that I am right and it should be the opposite?

2022-06-28 16:12 UTC, gunhanb commented
> 

Ahh I confused myself! The original documentation is correct, that is when unacceptable is provided, the vector length is of
length 4, and otherwise it is be 3.

2022-06-28 16:24 UTC, wwojciech commented
> > 
> 
> Ahh I confused myself! The original documentation is correct, that is when unacceptable is provided, the vector length is of length 4, and otherwise it is be 3.

Got it, Tx! So then, there is some serious bug in the `nextBest-NextBestNCRMLoss` method implementation, as it fails for the valid example you provided in `Rules-method-nextBest-NextBestNCRMLoss.R` file.
The failure is: `Error in nextBest@losses %*% t(probMat) : non-conformable arguments`, so I would say that it expects that length of `losses` is equal `3`, when `unacceptable` is provided. Can you pl. check this? Tx!

2022-06-28 17:43 UTC, danielinteractive commented
@gunhanb @wwojciech maybe again would be more efficient to schedule  a short meeting to iron this out :-)

2022-07-04 09:02 UTC, wwojciech requested changes
Hi @gunhanb - I think that 3 slots that I pointed out in the definition of `NextBestNCRMLoss` are obsolete. Then the implementation of `nextBest` methods needs to be adjusted accordingly. Feel free to reach out in case of any additional questions or doubts. Tx!

2022-07-04 09:02 UTC, wwojciech commented on R/Rules-methods.R
> +      (samples_prob > nextBest@overdose[1]) & (samples_prob <= nextBest@overdose[2])
But the `nextBest@overdose`, `nextBest@target` are never set when creating `nextBest` class object with `NextBestNCRMLoss()` user constructor. Something is wrong here.

2022-07-06 12:31 UTC, wwojciech approved these changes
Hi @gunhanb, It looks good now, Thanks a lot!

2022-07-06 12:31 UTC, merged