664: Add `DataGrouped` class
Roche/crmPack pull request #665
Opened 2023-08-25 13:24 UTC by danielinteractive

closes #664

2023-08-29 13:28 UTC, Puzzled-Face requested changes

2023-08-29 13:28 UTC, Puzzled-Face commented on tests/testthat/helper-data.R
A thought: The new `.DefaultXXXX()` constructors could probably replace the utility functions in the future.

2023-08-29 13:28 UTC, Puzzled-Face commented on R/Data-class.R
Please add a `.DefaultDataGrouped` constructor.

2023-08-29 13:55 UTC, danielinteractive commented on R/Data-class.R
thx, done

2023-08-29 13:55 UTC, danielinteractive commented on tests/testthat/helper-data.R
maybe, but typically the default constructors produce pretty "empty" objects while for tests we typically need more "realistic" objects

2023-08-30 09:47 UTC, Puzzled-Face approved these changes

2023-08-30 09:47 UTC, merged